spring.application.name=backend

# Conexão com o PostgreSQL (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/conectavida
spring.datasource.username=admin
spring.datasource.password=password123

# Configurações do JPA e Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true